import Head from 'next/head'
import Banner from '../components/banner/banner'
import Navbar from '../components/navbar/navbar'
export default function Home() {
  return (
    <div >
      <Head>
        <title>CowboysTimeverse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Banner
      title="Some Stories Can't Explain With Words"
      subTitle="The West Wild Cowboys Culture is Still Alive!"
      imgUrl="./static/background.gif"
      />
    </div>
  )
}
